package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int stt=0;
	private String email;
	private String passwordAccount;
	private Date expirationDate;
	private String expiration_date;
	private String phone;
	private Set accountChilds = new HashSet(0);

	public Account() {
	}

	public Account(String email) {
		this.email = email;
	}

	public Account(String email, String passwordAccount, Date expirationDate, String phone, Set<?> accountChilds) {
		this.email = email;
		this.passwordAccount = passwordAccount;
		this.expirationDate = expirationDate;
		this.phone = phone;
		this.accountChilds = accountChilds;
	}
	public Account(int stt, String email, String passwordAccount, Date expirationDate, String phone, Set<?> accountChilds) {
		this.email = email;
		this.passwordAccount = passwordAccount;
		this.expirationDate = expirationDate;
		this.phone = phone;
		this.accountChilds = accountChilds;
		this.stt ++;
	}
	public Account(String email, String passwordAccount, String expiration_date, String phone) {
		this.email = email;
		this.passwordAccount = passwordAccount;
		this.expiration_date = expiration_date;
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	public int getStt() {
		return this.stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	public String getPasswordAccount() {
		return this.passwordAccount;
	}

	public void setPasswordAccount(String passwordAccount) {
		this.passwordAccount = passwordAccount;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}
	public String getExpiration_date() {
		return this.expiration_date;
	}

	public void setExpiration_date(String expiration_date) {
		this.expiration_date = expiration_date;
	}
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getAccountChilds() {
		return this.accountChilds;
	}

	public void setAccountChilds(Set accountChilds) {
		this.accountChilds = accountChilds;
	}

}
