package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;

/**
 * ActivitiHistoryMovie generated by hbm2java
 */
public class ActivitiHistoryMovie implements java.io.Serializable {

	private ActivitiHistoryMovieId id;
	private AccountChild accountChild;
	private Movie movie;
	private Byte likebtn;
	private Byte dislikebtn;
	private Byte saved;
	private Date createDate;

	public ActivitiHistoryMovie() {
	}

	public ActivitiHistoryMovie(ActivitiHistoryMovieId id, AccountChild accountChild, Movie movie) {
		this.id = id;
		this.accountChild = accountChild;
		this.movie = movie;
	}

	public ActivitiHistoryMovie(ActivitiHistoryMovieId id, AccountChild accountChild, Movie movie, Byte likebtn,
			Byte dislikebtn, Byte saved, Date createDate) {
		this.id = id;
		this.accountChild = accountChild;
		this.movie = movie;
		this.likebtn = likebtn;
		this.dislikebtn = dislikebtn;
		this.saved = saved;
		this.createDate = createDate;
	}

	public ActivitiHistoryMovieId getId() {
		return this.id;
	}

	public void setId(ActivitiHistoryMovieId id) {
		this.id = id;
	}

	public AccountChild getAccountChild() {
		return this.accountChild;
	}

	public void setAccountChild(AccountChild accountChild) {
		this.accountChild = accountChild;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public Byte getLikebtn() {
		return this.likebtn;
	}

	public void setLikebtn(Byte likebtn) {
		this.likebtn = likebtn;
	}

	public Byte getDislikebtn() {
		return this.dislikebtn;
	}

	public void setDislikebtn(Byte dislikebtn) {
		this.dislikebtn = dislikebtn;
	}

	public Byte getSaved() {
		return this.saved;
	}

	public void setSaved(Byte saved) {
		this.saved = saved;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
