package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;

/**
 * ActivitiHistoryMovie generated by hbm2java
 */
public class ActivitiHistoryMovie implements java.io.Serializable {

	private Byte accountId;
	private Byte movieId;
	private Byte likebtn;
	private Byte dislikebtn;
	private Byte saved;
	private Date createDate;

	public ActivitiHistoryMovie() {
	}

	public ActivitiHistoryMovie( Byte accountId, Byte movieId) {
		this.accountId = accountId;
		this.movieId = movieId;
	}

	public ActivitiHistoryMovie(Byte accountId, Byte movieId, Byte likebtn,
			Byte dislikebtn, Byte saved, Date createDate) {
		this.accountId = accountId;
		this.movieId = movieId;
		this.likebtn = likebtn;
		this.dislikebtn = dislikebtn;
		this.saved = saved;
		this.createDate = createDate;
	}

	

	public Byte getAccountId() {
		return accountId;
	}

	public void setAccountId(Byte accountId) {
		this.accountId = accountId;
	}

	public Byte getMovieId() {
		return movieId;
	}

	public void setMovieId(Byte movieId) {
		this.movieId = movieId;
	}

	public Byte getLikebtn() {
		return this.likebtn;
	}

	public void setLikebtn(Byte likebtn) {
		this.likebtn = likebtn;
	}

	public Byte getDislikebtn() {
		return this.dislikebtn;
	}

	public void setDislikebtn(Byte dislikebtn) {
		this.dislikebtn = dislikebtn;
	}

	public Byte getSaved() {
		return this.saved;
	}

	public void setSaved(Byte saved) {
		this.saved = saved;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
