// default package
// Generated Apr 16, 2021, 3:06:54 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * ActivitiHistoryMovie generated by hbm2java
 */
public class ActivitiHistoryMovie implements java.io.Serializable {

	private ActivitiHistoryMovieId id;
	private AccountChild accountChild;
	private Movie movie;
	private Boolean likebtn;
	private Boolean dislikebtn;
	private Boolean saved;
	private Date createDate;

	public ActivitiHistoryMovie() {
	}

	public ActivitiHistoryMovie(ActivitiHistoryMovieId id, AccountChild accountChild, Movie movie) {
		this.id = id;
		this.accountChild = accountChild;
		this.movie = movie;
	}

	public ActivitiHistoryMovie(ActivitiHistoryMovieId id, AccountChild accountChild, Movie movie, Boolean likebtn,
			Boolean dislikebtn, Boolean saved, Date createDate) {
		this.id = id;
		this.accountChild = accountChild;
		this.movie = movie;
		this.likebtn = likebtn;
		this.dislikebtn = dislikebtn;
		this.saved = saved;
		this.createDate = createDate;
	}

	public ActivitiHistoryMovieId getId() {
		return this.id;
	}

	public void setId(ActivitiHistoryMovieId id) {
		this.id = id;
	}

	public AccountChild getAccountChild() {
		return this.accountChild;
	}

	public void setAccountChild(AccountChild accountChild) {
		this.accountChild = accountChild;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public Boolean getLikebtn() {
		return this.likebtn;
	}

	public void setLikebtn(Boolean likebtn) {
		this.likebtn = likebtn;
	}

	public Boolean getDislikebtn() {
		return this.dislikebtn;
	}

	public void setDislikebtn(Boolean dislikebtn) {
		this.dislikebtn = dislikebtn;
	}

	public Boolean getSaved() {
		return this.saved;
	}

	public void setSaved(Boolean saved) {
		this.saved = saved;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
