package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

/**
 * ActivitiHistoryMovieId generated by hbm2java
 */
public class ActivitiHistoryMovieId implements java.io.Serializable {

	private byte accountId;
	private int movieId;

	public ActivitiHistoryMovieId() {
	}

	public ActivitiHistoryMovieId(byte accountId, int movieId) {
		this.accountId = accountId;
		this.movieId = movieId;
	}

	public byte getAccountId() {
		return this.accountId;
	}

	public void setAccountId(byte accountId) {
		this.accountId = accountId;
	}

	public int getMovieId() {
		return this.movieId;
	}

	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivitiHistoryMovieId))
			return false;
		ActivitiHistoryMovieId castOther = (ActivitiHistoryMovieId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getMovieId() == castOther.getMovieId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getMovieId();
		return result;
	}

}
