package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor implements java.io.Serializable {

	private int actorId;
	private String firstName;
	private String lastName;
	private Byte director;
	private Date lastUpdate;
	private Set actorMovies = new HashSet(0);

	public Actor() {
	}

	public Actor(int actorId) {
		this.actorId = actorId;
	}

	public Actor(int actorId, String firstName, String lastName, Byte director, Date lastUpdate, Set actorMovies) {
		this.actorId = actorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.director = director;
		this.lastUpdate = lastUpdate;
		this.actorMovies = actorMovies;
	}
	public Actor(int actorId, String firstName, String lastName, Byte director) {
		this.actorId = actorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.director = director;

	}
	public int getActorId() {
		return this.actorId;
	}

	public void setActorId(int actorId) {
		this.actorId = actorId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Byte getDirector() {
		return this.director;
	}

	public void setDirector(Byte director) {
		this.director = director;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getActorMovies() {
		return this.actorMovies;
	}

	public void setActorMovies(Set actorMovies) {
		this.actorMovies = actorMovies;
	}

}
