// default package
// Generated Apr 16, 2021, 3:06:54 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * ActorMovie generated by hbm2java
 */
public class ActorMovie implements java.io.Serializable {

	private int stt;
	private Actor actor;
	private Movie movie;
	private Date lastUpdate;

	public ActorMovie() {
	}

	public ActorMovie(int stt, Actor actor, Movie movie) {
		this.stt = stt;
		this.actor = actor;
		this.movie = movie;
	}

	public ActorMovie(int stt, Actor actor, Movie movie, Date lastUpdate) {
		this.stt = stt;
		this.actor = actor;
		this.movie = movie;
		this.lastUpdate = lastUpdate;
	}

	public int getStt() {
		return this.stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
