package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie implements java.io.Serializable {

	private int movieId;
	private String nameMovie;
	private String descriptionMovie;
	private String image;
	private String trailer;
	private String video;
	private String lo;
	private String maturityRating;
	private Date lastUpdate;
	private String duration;
	private Byte topHot;
	private Set banners = new HashSet(0);
	private Set detailMovies = new HashSet(0);
	private Set seasonMovies = new HashSet(0);
	private Set activitiHistoryMovies = new HashSet(0);
	private Set actorMovies = new HashSet(0);

	public Movie() {
	}

	public Movie(int movieId) {
		this.movieId = movieId;
	}

	public Movie(int movieId, String nameMovie, String descriptionMovie, String image, String trailer, String video,
			String lo, String maturityRating, Date lastUpdate, String duration, Byte topHot, Set banners,
			Set detailMovies, Set seasonMovies, Set activitiHistoryMovies, Set actorMovies) {
		this.movieId = movieId;
		this.nameMovie = nameMovie;
		this.descriptionMovie = descriptionMovie;
		this.image = image;
		this.trailer = trailer;
		this.video = video;
		this.lo = lo;
		this.maturityRating = maturityRating;
		this.lastUpdate = lastUpdate;
		this.duration = duration;
		this.topHot = topHot;
		this.banners = banners;
		this.detailMovies = detailMovies;
		this.seasonMovies = seasonMovies;
		this.activitiHistoryMovies = activitiHistoryMovies;
		this.actorMovies = actorMovies;
	}
	public Movie(int movieId, String nameMovie, String descriptionMovie, String image, String trailer, String video,
			String lo, String maturityRating, String duration, Byte topHot) {
		this.movieId = movieId;
		this.nameMovie = nameMovie;
		this.descriptionMovie = descriptionMovie;
		this.image = image;
		this.trailer = trailer;
		this.video = video;
		this.lo = lo;
		this.maturityRating = maturityRating;
		this.duration = duration;
		this.topHot = topHot;
	}

	public int getMovieId() {
		return this.movieId;
	}

	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}

	public String getNameMovie() {
		return this.nameMovie;
	}

	public void setNameMovie(String nameMovie) {
		this.nameMovie = nameMovie;
	}

	public String getDescriptionMovie() {
		return this.descriptionMovie;
	}

	public void setDescriptionMovie(String descriptionMovie) {
		this.descriptionMovie = descriptionMovie;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getTrailer() {
		return this.trailer;
	}

	public void setTrailer(String trailer) {
		this.trailer = trailer;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public String getLo() {
		return this.lo;
	}

	public void setLo(String lo) {
		this.lo = lo;
	}

	public String getMaturityRating() {
		return this.maturityRating;
	}

	public void setMaturityRating(String maturityRating) {
		this.maturityRating = maturityRating;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public Byte getTopHot() {
		return this.topHot;
	}

	public void setTopHot(Byte topHot) {
		this.topHot = topHot;
	}

	public Set getBanners() {
		return this.banners;
	}

	public void setBanners(Set banners) {
		this.banners = banners;
	}

	public Set getDetailMovies() {
		return this.detailMovies;
	}

	public void setDetailMovies(Set detailMovies) {
		this.detailMovies = detailMovies;
	}

	public Set getSeasonMovies() {
		return this.seasonMovies;
	}

	public void setSeasonMovies(Set seasonMovies) {
		this.seasonMovies = seasonMovies;
	}

	public Set getActivitiHistoryMovies() {
		return this.activitiHistoryMovies;
	}

	public void setActivitiHistoryMovies(Set activitiHistoryMovies) {
		this.activitiHistoryMovies = activitiHistoryMovies;
	}

	public Set getActorMovies() {
		return this.actorMovies;
	}

	public void setActorMovies(Set actorMovies) {
		this.actorMovies = actorMovies;
	}

}
