package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SeasonMovie generated by hbm2java
 */
public class SeasonMovie implements java.io.Serializable {

	private byte seasonId;
	private Movie movie;
	private Date lastUpdate;
	private int movie_id;
	private String last_update;


	public String getLast_update() {
		return last_update;
	}

	public void setLast_update(String last_update) {
		this.last_update = last_update;
	}

	private Set seriesMovies = new HashSet(0);

	public SeasonMovie() {
	}

	public SeasonMovie(byte seasonId, Movie movie) {
		this.seasonId = seasonId;
		this.movie = movie;
	}

	public SeasonMovie(byte seasonId, Movie movie, Date lastUpdate, Set seriesMovies) {
		this.seasonId = seasonId;
		this.movie = movie;
		this.lastUpdate = lastUpdate;
		this.seriesMovies = seriesMovies;
	}
	
	public SeasonMovie(byte seasonId, int movie_id) {
		this.seasonId = seasonId;
		this.movie_id = movie_id;
	}

	public byte getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(byte seasonId) {
		this.seasonId = seasonId;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}
	
	public int getMovie_id() {
		return movie_id;
	}

	public void setMovie_id(int movie_id) {
		this.movie_id = movie_id;
	}
	
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getSeriesMovies() {
		return this.seriesMovies;
	}

	public void setSeriesMovies(Set seriesMovies) {
		this.seriesMovies = seriesMovies;
	}

}
