package model;
// default package
// Generated Apr 27, 2021, 3:04:25 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;

/**
 * SeriesMovie generated by hbm2java
 */
public class SeriesMovie implements java.io.Serializable {

	private int seriesId;
	private SeasonMovie seasonMovie;
	private String descriptionSeries;
	private byte season_id;
	private String last_update;
	public String getLast_update() {
		return last_update;
	}

	public void setLast_update(String last_update) {
		this.last_update = last_update;
	}

	public byte getSeason_id() {
		return season_id;
	}

	public void setSeason_id(byte season_id) {
		this.season_id = season_id;
	}

	private String duration;
	private String video;
	private Date lastUpdate;

	public SeriesMovie() {
	}

	public SeriesMovie(int seriesId, SeasonMovie seasonMovie) {
		this.seriesId = seriesId;
		this.seasonMovie = seasonMovie;
	}

	public SeriesMovie(int seriesId, SeasonMovie seasonMovie, String descriptionSeries, String duration, String video,
			Date lastUpdate) {
		this.seriesId = seriesId;
		this.seasonMovie = seasonMovie;
		this.descriptionSeries = descriptionSeries;
		this.duration = duration;
		this.video = video;
		this.lastUpdate = lastUpdate;
	}
	public SeriesMovie(int seriesId, byte season_id, String descriptionSeries, String duration, String video) {
		this.seriesId = seriesId;
		this.season_id = season_id;
		this.descriptionSeries = descriptionSeries;
		this.duration = duration;
		this.video = video;
	}

	public int getSeriesId() {
		return this.seriesId;
	}

	public void setSeriesId(int seriesId) {
		this.seriesId = seriesId;
	}

	public SeasonMovie getSeasonMovie() {
		return this.seasonMovie;
	}

	public void setSeasonMovie(SeasonMovie seasonMovie) {
		this.seasonMovie = seasonMovie;
	}

	public String getDescriptionSeries() {
		return this.descriptionSeries;
	}

	public void setDescriptionSeries(String descriptionSeries) {
		this.descriptionSeries = descriptionSeries;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
