package model;

// default package
// Generated Apr 23, 2021, 2:11:14 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private String email;
	private String passwordAccount;
	private Date expirationDate;
	private String phone;
	private Set accountChilds = new HashSet(0);

	public Account() {
	}

	public Account(String email) {
		this.email = email;
	}

	public Account(String email, String passwordAccount, Date expirationDate, String phone, Set accountChilds) {
		this.email = email;
		this.passwordAccount = passwordAccount;
		this.expirationDate = expirationDate;
		this.phone = phone;
		this.accountChilds = accountChilds;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswordAccount() {
		return this.passwordAccount;
	}

	public void setPasswordAccount(String passwordAccount) {
		this.passwordAccount = passwordAccount;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getAccountChilds() {
		return this.accountChilds;
	}

	public void setAccountChilds(Set accountChilds) {
		this.accountChilds = accountChilds;
	}

}
