package model;

// default package
// Generated Apr 23, 2021, 2:11:14 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * SeriesMovie generated by hbm2java
 */
public class SeriesMovie implements java.io.Serializable {

	private int seriesId;
	private SeasonMovie seasonMovie;
	private String descriptionSeries;
	private String duration;
	private String video;
	private Date lastUpdate;

	public SeriesMovie() {
	}

	public SeriesMovie(int seriesId, SeasonMovie seasonMovie) {
		this.seriesId = seriesId;
		this.seasonMovie = seasonMovie;
	}

	public SeriesMovie(int seriesId, SeasonMovie seasonMovie, String descriptionSeries, String duration, String video,
			Date lastUpdate) {
		this.seriesId = seriesId;
		this.seasonMovie = seasonMovie;
		this.descriptionSeries = descriptionSeries;
		this.duration = duration;
		this.video = video;
		this.lastUpdate = lastUpdate;
	}

	public int getSeriesId() {
		return this.seriesId;
	}

	public void setSeriesId(int seriesId) {
		this.seriesId = seriesId;
	}

	public SeasonMovie getSeasonMovie() {
		return this.seasonMovie;
	}

	public void setSeasonMovie(SeasonMovie seasonMovie) {
		this.seasonMovie = seasonMovie;
	}

	public String getDescriptionSeries() {
		return this.descriptionSeries;
	}

	public void setDescriptionSeries(String descriptionSeries) {
		this.descriptionSeries = descriptionSeries;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
